# -*- coding: utf-8 -*-
"""Two Pointers : Merge Two Arrays

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CWt9CMRP_xBWodHfafIgWuJV3jYj3Pta
"""

n,m = map(int, input().split())
a = list(map(int, input().split()))
b = list(map(int, input().split()))

i,j = 0,0

while (i<n and j<m):
  if a[i]<b[j]:
    print(a[i], end="\t ")
    i+=1

  else:
    print(b[j], end="\t")
    j+=1

while i<n:
  print(a[i], end="\t")
  i+=1
while j<m:
  print(b[j], end="\t")
  j+=1
